<a href="https://colab.research.google.com/github/ashutoshghodke/ashutoshghodke/blob/main/CDAC_DBDA_2022_NumPY_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([[10,20,30],[40,45,50,60],[70,80]])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [ ]:
a.shape

(3,)

In [ ]:
a.ndim

1

In [ ]:
a.shape

(3,)

In [ ]:
a=np.array([[10,20,30],[40,45,50]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 3)

In [ ]:
a.size

6

In [ ]:
a=np.array([[10,20,30],[40,50,60]])
for row in a:
    for element in row:
        print(element,end=" ")
    print()


10 20 30 
40 50 60 


In [ ]:
a=np.array([[10,20,30],[40,50],[60,70,80,90,100]])
for row in a:
    for element in row:
        print(element,end=" ")
    print()


10 20 30 
40 50 
60 70 80 90 100 


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [ ]:
a=np.array([[10,20,30],[40,50],[60,70,80,90,100]])
#print number of elements in each row and then print row element by element one after other
i=1
for row in a:
    print("Row",i,"has",len(row),"elements")
    for element in row:
        print(element)
    i+=1
    

Row 1 has 3 elements
10
20
30
Row 2 has 2 elements
40
50
Row 3 has 5 elements
60
70
80
90
100


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [ ]:
#print matrix using index only
a=np.array([[10,20,30],[40,50],[60,70,80,90,100]])
for r in range(len(a)):
    for c in range(len(a[r])):
        print(a[r][c],end=" ")
    print()


10 20 30 
40 50 
60 70 80 90 100 


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


In [ ]:
for item in np.nditer(a[::]):#n X m only
    print(item)

10
20
30
40
45
50


In [ ]:
a

array([[10, 20, 30],
       [40, 45, 50]])

In [ ]:
a[1,2]#[rowindex,columnindex]

50

In [ ]:
a=np.arange(1,21,2)# start ,end,step

In [ ]:
a=np.arange(21)# start=0,end,step=1

In [ ]:
a=np.arange(1,11)
a2d=a.reshape(5,2)#nXm--->total elements
print(a)
print(a2d)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#5X5 filled with all odd numbers from 1 to needed
a=np.arange(1,50,2).reshape(5,5)
print(a)


[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]


In [ ]:
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [ ]:
a=np.arange(1,21).reshape(4,5)

In [ ]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
a[3:1:-1,4:1:-1]#[row start:end:step,column start:end:step]

array([[20, 19, 18],
       [15, 14, 13]])

In [ ]:
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[1,2,3],[4,5,6]])

In [ ]:
a3=a1*a2

In [ ]:
a3

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
a3

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
a1/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [ ]:
a=np.linspace(1,10,5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
from numpy import random

In [ ]:
x=random.randint(7)#0 to 6
print(x)

6


In [ ]:
x=random.randint(1,7)#1 to 6
print(x)

5


In [ ]:
x=random.randint(101,size=(5,10))#start,end,n X m
print(x)

[[25 66 35 31  8 12 43 18 26 90]
 [44 18 30 76 34 19 23 14  4 81]
 [85 42 62 42 45 19  2 72 19 11]
 [92 85 17 87 65 34 44 26 20 45]
 [58 49 72 74 18 87 45 80 19 56]]


In [ ]:
#generate 10 unique random numbers from 1 to 100 in a list
from numpy import random
l=[]#list
while len(l)<10:
    no=random.randint(1,100)
    if no not in l:
        l.append(no)
print(l)


[31, 62, 32, 25, 76, 59, 3, 27, 21, 50]


In [ ]:
nlist=['amar','atharv','aman','abhijit','rahul']
random.choice(nlist)

'aman'

In [ ]:
nlist=['amar','atharv','aman','abhijit','rahul']
random.choice(nlist,size=(3,3))

array([['amar', 'abhijit', 'aman'],
       ['rahul', 'atharv', 'abhijit'],
       ['abhijit', 'atharv', 'abhijit']], dtype='<U7')

In [ ]:
m=random.rand()#float
print(m)

0.05937959891031708


In [ ]:
m=random.rand(3,7)#float
print(m)

[[0.8923286  0.98453126 0.03987969 0.1225169  0.15711152 0.08462443
  0.13305794]
 [0.2398349  0.68854552 0.15706292 0.3597582  0.26808685 0.79359952
  0.89797601]
 [0.84586904 0.64227663 0.74227439 0.47988493 0.45149758 0.65102938
  0.8355603 ]]


In [ ]:
x=random.randint(101,size=(5,5))#start,end,n X m
print(x)

[[ 56  23  37  21 100]
 [ 86  99  61  20  58]
 [ 94  26  57  73  35]
 [ 52  99  72  21  47]
 [ 37  66  15 100  24]]


In [ ]:
np.sort(x,axis=1)

array([[ 21,  23,  37,  56, 100],
       [ 20,  58,  61,  86,  99],
       [ 26,  35,  57,  73,  94],
       [ 21,  47,  52,  72,  99],
       [ 15,  24,  37,  66, 100]])

In [ ]:
x=random.randint(101,size=(4,4))#start,end,n X m
print(x)

[[92 71 26 52]
 [ 6 14 36 38]
 [53 16 25 13]
 [19 63 77 20]]


In [ ]:
np.where(x%2==0)#returns index that satisfies the condition

(array([0, 0, 0, 1, 1, 1, 1, 2, 3]), array([0, 2, 3, 0, 1, 2, 3, 1, 3]))

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])