<a href="https://colab.research.google.com/github/ashutoshghodke/ashutoshghodke/blob/main/python_interview_qst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#write a python program to find out the common letters in two string
# 1)naina
# 2)reena
def common_letters():
  str1=input("enter 1st str")
  str2=input("enter 2nd str")
  s1=set(str1)
  s2=set(str2)
  list=s1 & s2

  print(list)


common_letters()

KeyboardInterrupt: ignored

In [ ]:
#write a python program to count the frequency of words
# Appering in a string

def count():
  str=input("enter a str")
  s1=sorted(set(str.split()))
  s2=str.split()

  for i in s1:
    print(i,"--->",s2.count(i))


In [ ]:
count()

enter a strab ab ba gh hg
ab ---> 2
ba ---> 1
gh ---> 1
hg ---> 1


In [ ]:
#write a python program  to convert two list into dict
# l1=[naina,kimi,sheena]
# l2=[5212,5246,8652]

def list_to_dict():
  key=[5212,5246,8652]
  values=['naina','kimi','sheena']
  result=dict(zip(key,values))
  print(result)
  print(type(result))


list_to_dict()


{5212: 'naina', 5246: 'kimi', 8652: 'sheena'}
<class 'dict'>


In [ ]:
#dict to tuple
def dict_to_tuple():
  x={5212: 'naina', 5246: 'kimi', 8652: 'sheena'}
  for i in x.items():
    print(i)
    print(type(i))

dict_to_tuple()

(5212, 'naina')
<class 'tuple'>
(5246, 'kimi')
<class 'tuple'>
(8652, 'sheena')
<class 'tuple'>


In [ ]:
#find missing no in an aaray(using summation and XOR method)
#1|2|4|5|6|7 ---missimg no is 3
#using summation
def get_miising_no():
  n=7
  array=[1,2,4,5,6,7]
  total=n*(n+1)/2
  s=sum(array)
  missedno=total-s
  print(missedno)

get_miising_no()


## using xor
#not importanat by xor so leave it


3.0


In [ ]:
#find out pairs with given sum value of na aaray

def two_sum(array,summ,len):
  for i in range (len):
    for j in range(i,len):
      if(array[i]+array[j]==summ):
        print(array[i],array[j])


array = [5, 2, 3, 4, 1, 6, 7]
summ = 7
two_sum(array,summ,len(array))

5 2
3 4
1 6


In [ ]:

#remove duplicates
l1=[1,2,3,4,1,2,3,5,1,1,2,33,3]
l2=(set(l1))
print(l2)

# #using array iteration
l1=[1,2,3,4,1,2,3,5,1,1,2,33,3]
l=[]
for i in l1:
  if( i not in l):
    l.append(i)
print(l)

# #lambda function
l1=[1,2,3,4,1,2,3,5,1,1,2,33,3]
rmv_dupli=lambda l1:set(l1)
print(rmv_dupli(l1))


## using dictionary
dict={
    'car':["ford","toyota","ford","toyota"],
    'brand':["ecosport","fortuner","ecosport","fortuner"]

}

dict1={}

for keys,values in dict.items():
  dict1[keys]=set(values)
print(dict1)


## symetric difference
s1={1,2,3,4}
s2={2,1,4,7}
rmv=s1.symmetric_difference(s2)
print(rmv)

{3, 7}


In [ ]:
#How to Reverse a List in Python
## BY ITERATION
b=[]
a=[10,52,25,45,89,56,35,78,85,86,5]
for i in range (len(a)-1,-1,-1):
  b.append(a[i])
print(b)

## BY SLICING
a=[10,52,25,45,89,56,35,78,85,86,5]
b=a[::-1]
print(b)

## BY REVERSE FUNCTION
a=[10,52,25,45,89,56,35,78,85,86,5]
a.reverse()
print(a)

[5, 86, 85, 78, 35, 56, 89, 45, 25, 52, 10]


In [ ]:
## Length of Last Word - Algorithm /Code in Python

a="ashutosh ghodkepatil"
b=a.split()
c=b[1]
print(c)
print(len(c))

ghodkepatil
11


In [ ]:
#write a Python program to check whether a given number is an even or an odd number.
number=int(input("enter a number"))
if number % 2==0:
  print("the number is even")
else:
  print("the number is odd ")

enter a number82
the number is even


In [ ]:
## write a Python program to check prime number using for loop

num=int(input("enter a number "))
if num<2:
  print("not a prime number")
else:
  for i in range(2,num):
    if num%i==0:
      print("not a prime number")
      break
  else:
      print("it is  a prime number")

enter a number 101
it is  a prime number


In [ ]:
## Check Alphabet or Not

alpha=input("enter a alphabet")
if alpha >="a" and alpha<="z":
  print("it is alphabet")
elif alpha>="A" and alpha <="Z":
  print("it is  albhabet")
else:
  print("it is not alphabet")

enter a alphabetwedfrgh
it is alphabet


In [ ]:
## Python Program to Check Vowel or Consonant
alpha=input("enter a alphabet")
vowels=["a","e","i","o","u","A","E","I","O","U"]
if alpha in vowels:

  print("alphabet is vowel")
else:
  print("alphabet is consonant")

enter a alphabetAIE
alphabet is consonant


In [ ]:
## Python Program to Check Leap Year

year=int(input("enter a year"))
if (year%400==0 & year%100!=0) or(year%4==0):
  print("year is leap")
else:
  print("year is ordinary")

enter a year1958
year is ordinary


In [ ]:
#Check Reverse Equals Original in Python
i=int(input("enter a num"))
rev=0
while(i>0):
  rev=(rev*10)+i%10
  i=i//10
print("reverse number is",rev)

enter a num8645
reverse number is 5468


In [ ]:
#Python Program to Check Armstrong Number

num=int(input("enter a number"))
order=len(str(num))
sum=0
temp=num

while temp>0:
  digit= temp%10
  power=digit**order
  sum=sum+power
  temp //=10

if sum==num:
  print("it is an armstrong number")

else:
  print("it is not an armstrong number")

enter a number407
it is an armstrong number


In [ ]:
#Check Even or Odd Number

def even_odd():
  num1=int(input("enter a number "))
  if num1%2==0:
    print("number is even")

  else:
    print("number is odd ")


even_odd()

enter a number 48
number is even


In [ ]:
def primeno():
  num1=int(input("enter a number"))
  if num1<2:
    print ("number is not a prime number ")
  else:

    for i in range (2,num1):
      if num1%i==0:
        print("number is not a prime number")
        break
      else:
        print("number is a prime number")
        break



primeno()



enter a number13
number is a prime number


In [ ]:
#Check Alphabet or Not
s1=input("eneter alphabets ")
for i in s1:
  if i>="a" or i<="z":
    print("input is alpha ")
    break
  elif i>="A" or i<="Z":
    print("input is alpha ")
    break
  else:
    print("input is not alpha")





eneter alphabets 8520
input is alpha 


In [ ]:
#Check Leap Year

year=int(input("enter a year"))
if (year%4==0 and year%100!=0) or (year%400==0):
  print("year is leap year ")
else:
  print("year is ordinary year")


enter a year2023
year is ordinary year


In [ ]:
#Check Reverse Equals Original in Python

num1=int(input("enetr a num"))
org=num1
rev=0

while num1>0:
  rem=num1%10
  rev=rem+(rev*10)
  num1=int(num1/10)
if num1==rev:
  print("the number is equal to its reverse ")
else:
  print("the number is  not equal to its reverse ")

In [ ]:
#Python Program to Check Armstrong Number

num=int(input("enter a number"))
order=len(str(num))
sum=0
temp=num

while temp>0:
  digit= temp%10
  power=digit**order
  sum=sum+power
  temp //=10

if sum==num:
  print("it is an armstrong number")

else:
  print("it is not an armstrong number")

In [ ]:
##  Fibonacci  series
def fibo(n):
  prevno=0
  currentno=1
  for i in range(1,n):
    prevprevno=prevno
    prevno=currentno
    currentno=prevprevno+prevno
  return currentno


fibo(45)



1134903170

In [ ]:
# PALIMDROME NUMBER
num=int(input("enter a num"))
org=num
rev=0


while num>0:
  rem=num%10
  rev=(rev*10)+rem
  num=num//10

if org==rev:
  print("num is palindrome num")
else:
  print("num is not a palindrome num")

enter a num202
num is palindrome num


In [ ]:
## factorial of num
def fact(num):
  if num==1:
    return 1

  else:
    return num*fact(num-1)


fact(4)

24

In [ ]:
## pattern printing
for i in range(1,10):
  print("*"*i)
print("@@@@@@@@@@@@@@@@@@@@@@")
## reverse
for i in range(10,0,-1):
  print("*"*i)

*
**
***
****
*****
******
*******
********
*********
@@@@@@@@@@@@@@@@@@@@@@
**********
*********
********
*******
******
*****
****
***
**
*


In [ ]:
for i in range(1,10):

    print(" "*(10-i),("*"*i))
print("@@@@@@@@@@@@@@@@@@@@@@@@@")
for i in range(1,10):

    print(" "*(10-i),("*"*i))

          *
         **
        ***
       ****
      *****
     ******
    *******
   ********
  *********
@@@@@@@@@@@@@@@@@@@@@@@@@
          *
         **
        ***
       ****
      *****
     ******
    *******
   ********
  *********


In [ ]:
## Remove duplicates in list
# l=[1, 2, 3, 4, 5, 4, 3, 2, 1, 2]
# newl=set(l)
# new2=list(newl)
# print(new2)

# or
l=[1, 2, 3, 4, 5, 4, 3, 2, 1, 2]
mylist=[]
for i in l:
  if l[i] not in mylist:
    mylist.append(l[i])
print(mylist)


[2, 3, 4, 5]


In [ ]:
for i in range(1,8):
  print(" "*(8-i),("* "*i))


        * 
       * * 
      * * * 
     * * * * 
    * * * * * 
   * * * * * * 
  * * * * * * * 


In [ ]:
for i in range(5,0,-1):
  print(" "*(5-i),("* "*i))

 * * * * * 
  * * * * 
   * * * 
    * * 
     * 


In [ ]:
for i in range(1,8):
  print(" "*(8-i),("* "*i))

In [ ]:
##Diamond Pattern In Python Using For Loop

for i in range(0,8):
  print(" "*(8-i),"*" * (2*i+1))

for i in range(8,-1,-1):
  print(" "*(8-i),"*" * (2*i+1))

         *
        ***
       *****
      *******
     *********
    ***********
   *************
  ***************
 *****************
  ***************
   *************
    ***********
     *********
      *******
       *****
        ***
         *


In [ ]:
#Python Program for Floyd’s Triangle
row=int(input("enter no.of rows"))
num=1
for i in range(1,row+1):
  for j in range(1,i+1):
    print(num,end=' ')
    num=num+1
  print()

enter no.of rows20
1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 
16 17 18 19 20 21 
22 23 24 25 26 27 28 
29 30 31 32 33 34 35 36 
37 38 39 40 41 42 43 44 45 
46 47 48 49 50 51 52 53 54 55 
56 57 58 59 60 61 62 63 64 65 66 
67 68 69 70 71 72 73 74 75 76 77 78 
79 80 81 82 83 84 85 86 87 88 89 90 91 
92 93 94 95 96 97 98 99 100 101 102 103 104 105 
106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 
121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 
137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 
154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 
172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 
191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 


In [ ]:
keys = ["a", "b", "c"]
values = [2, 3, 4]

d=dict(zip(keys,values))
print(d)

{'a': 2, 'b': 3, 'c': 4}


In [ ]:
l=[10,50,58,35,28,65,48,89,92,48,99]
a=min(l)
b=max(l)
print(a,b)

10 99


In [ ]:
num=int(input("enter a num"))
if num<1:
  print("ni.is not a prime no")
else:
  for i in range(2,num):
    if num%i==0:
      print("no is not a prime no")
      break
    else:
      print("no is a prime no")
      break

enter a num30
no is not a prime no


In [ ]:
## Sorting elements in the list

mylist = [2,5,7,5,3,4,5,2]
mylist.sort()
mylist

[2, 2, 3, 4, 5, 5, 5, 7]

In [ ]:
# Find maximum number from an array

arr = [5,4,3,6,9]
d=max(arr)
d

9

In [ ]:
## find dublicate value and sort in accending order
mylist = [2,5,7,5,3,4,5,2]
mylist.sort()
s=set(mylist)
for i in s:
  if mylist.count(i)>=2:
    print(i)






2
5


In [ ]:
# Python program to find second largest number
list1 = [10, 20, 20, 4, 45, 45, 45, 99, 99]
new=[]
for i in list1:
  if i not in new:
    new.append(i)
a=sorted(new)
print(a[-2])

45


In [ ]:
## Fabonacci series
def febo(n):
  prevno=0
  currentno=1
  for i in range (1,n):
    prevprev=prevno
    prevno=currentno
    currentno=prevprev+prevno
  return currentno

febo(45)

1134903170

In [ ]:
# Checking string is palindrome or not
mystr="malam"
org=mystr
rev=mystr[::-1]
print(rev)

if org==rev:
  print("string is palindrome")
else:
  print("string is not palindrome")

malam
string is palindrome


In [ ]:
# Find the duplicate number in mylist

mylist = [1,1,1,1,2,3,3,6,9,7,6]
print(set([x for x in mylist if mylist.count(x)>1]))

{1, 3, 6}


In [ ]:
# Find the length of array without using len function
arr = [1,5,9,6,3]
counter = 0
for i in arr:
 counter = counter + 1

print(counter)

5


In [ ]:
for i in range(1,6):
  print("*"*i)

for i in range(6,0,-1):
  print("*"*i)

*
**
***
****
*****
******
*****
****
***
**
*


In [ ]:
# Diamond pattern
for i in range(1,8):
  print(" "*(8-i),"* "*i)

for i in range(8,0,-1):
  print(" "*(8-i),"* "*i)

        * 
       * * 
      * * * 
     * * * * 
    * * * * * 
   * * * * * * 
  * * * * * * * 
 * * * * * * * * 
  * * * * * * * 
   * * * * * * 
    * * * * * 
     * * * * 
      * * * 
       * * 
        * 


In [ ]:
for i in range (1,5):
  print(" "*(5-i),("* "*i))

for i in range (5,0,-1):
  print(" "*(5-i),("* "*i))

     * 
    * * 
   * * * 
  * * * * 
 * * * * * 
  * * * * 
   * * * 
    * * 
     * 


In [ ]:
def count():
  str=input("enter a str")
  s1=sorted(set(str.split()))
  s2=str.split()

  for i in s1:
    print(i,"-->",s2.count(i))

count()


enter a straa bb aaa aaa aa bb hhh hhh hhh
aa --> 2
aaa --> 2
bb --> 2
hhh --> 3


In [ ]:
num=int(input("enter a no"))
if num<2:
  print("not prime")
else:
  for i in range(2,num):
    if num%i==0:
      print("not prime")
      break
    else:
      print(" prime")
      break

enter a no12
not prime


In [ ]:
#sum of first 10 natural no
i=1
sum=0
while i<=10:
  sum=sum+i
  i+=1
print(sum)


55


In [ ]:
## PATTERN
for i in range(1,6):
  for j in range(1,i+1):
    print(i,end=" ")
  print()

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [ ]:
d=[12,25,45,36,63,52]
a=max(d)
a

63

In [ ]:
d=[12,25,45,36,63,52]
d.append([100,200,500])
print(d)


[12, 25, 45, 36, 63, 52, [100, 200, 500]]


In [ ]:
d=[12,25,45,36,63,52]
d.extend([100,200,300])
d

[12, 25, 45, 36, 63, 52, 100, 200, 300]

In [ ]:
d=[12,25,45,36,63,52,36]
# d.insert(-1,200)
# d.remove(200)
# d.pop(3)
# min(d)
# max(d)
# sorted(d)
# d.sort()
# d.reverse()
# a=d.index(36)
# a
# a=d.count(36)
# a


2

In [ ]:
num1=int(input("enter a num2"))
if num1%2==0:
  print("no is even")
else:
  print("no is odd")

enter a num2852012396385274145852
no is even


In [ ]:
print("welcome to election board ")
age=int(input("enter an age"))

if age>=18:
  print("you can vote")
else:
  print("you are not eligible")

welcome to election board 
enter an age15
you are not eligible


In [ ]:

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++.
## skip 5 and 8
 for i in range (0,10):
   if i==5 or i==8:
     continue
   print(i)

0
1
2
3
4
6
7
9


In [ ]:
l=[1,2,3]
b=""
v=[]
for i in l:
  b=b+str(i)
c=int(b)
d=c+1
print(d)
ff=str(d)
for i in ff:
  v.append(i)
print(v)


In [ ]:
#Print String in Python - Receive Multiple Strings and Print


no_of_string=int(input("enetr no of string "))

mylist=[]

for i in range(no_of_string):
  mystring=input()
  mylist.append(mystring)

print(mylist)

############### OR ##############

a=input("enter with valuse with space")
b=a.split()
print(b)
for i in range(len(b)) :
  b[i]=int(b[i])
print(b)



In [ ]:
#Find Length of String using for Loop

strr=input()
total=0
for i in strr:
  total=total+1
print(total)

In [ ]:
#Compare Two Strings using for Loop
s1=input()
s2=input()

ls1=len(s1)
ls2=len(s2)

for i in range(ls1):
  if s1[i]!=s2[i]:
    print("not equal")
    break
else:
  print("equal")


In [ ]:
#Concatenate Two Strings using join()
s1="ashutosh"
s2="ghodke"
s3=" ".join([s1,s2]) ## where " " acts as seprator
print(s3)

In [ ]:
l1=[10,20,30]
l2=[10,20,30]

for i in range(len(l1)):
  if l1[i]!=l2[i]:
    print("list are not same")

else:
        print("list are  same")



In [ ]:
#Python Reverse a String
s1=input()
s2=s1[::-1]
print(s2)

In [ ]:
print("Enter the String: ", end="")
str = input()

strRev = ""
for ch in str:
    strRev = ch + strRev

str = strRev
print("\nReverse =", str)

In [ ]:
str = "patil"

strRev = ""
for ch in str:
  strRev = ch + strRev
  str=strRev

print(str)


In [ ]:
#Swap Two Strings in Python
def swapp(a,b):
  return b,a


print(swapp("ram","sham"))


In [ ]:
a="dfgh"
b="dghgj"
a,b=b,a
print(a,b)

In [ ]:
##Uppercase to Lowercase Character using ASCII Value

up=input()
val_up=ord(up)
low=ord(up)+32
print(low)

#Lowercase to Uppercase Character using ASCII Value

low=input()
val_low=ord(low)
up=ord(low)-32
print(up)

In [ ]:
mystr=input()
substrr=input()
if substrr in mystr:
  print("yes")

else:
  print("no")


In [ ]:
#Count Occurrence of a Character in a String
strr=input()
ch=input()
sum=0
for i in range(len(strr)):
  if ch==strr[i]:
    sum=sum+1
print(ch,"==>",sum)

In [ ]:
#Find Frequency of Particular Character in String using count()
strr=input()
chh=input()
val=strr.count(chh)
print(val)

In [ ]:
# frequency of words appear in str
def count():
  strr=input()
  s1=sorted(set(strr.split()))
  s2=strr.split()

  for i in s1:
    print(i,"==>",s2.count(i))



count()

In [ ]:
#capitalize perticular word in str
strr="ashutosh balaji ghodke"
s1=strr.split()[1]
s2=s1.capitalize()
s3=strr.title()
print(s3)



In [ ]:
#Python Program to Print Smallest and Largest Word in String
s1="assd dfasdfg  hgfdsdfgf"
s2=s1.split()
r=[]
for i in s2:
  t=len(i)
  r.append(t)

print(r)
t=r.index(max(r))
print(s2[t])
f=r.index(min(r))
print(s2[f])

In [ ]:
print("Enter the String: ", end="")
str = input()

newstr = ""
for i in range(len(str)):
    ch = str[i]
    if ch != ' ':
        newstr = newstr + ch

str = newstr
print("\nString without Space:", str)

################### OR ########################
str = input()
s1=str.replace(" ","")
print(s1)


In [ ]:
       #Remove Duplicate Characters from String

strr=input()
s1=strr.split()
a=''
list=[]
for i in range(len(strr)):
  list.append(strr[i])
a=(set(list))
d=''.join(a)
print(d)

#################### OR ###################
s1="aasshhhyy"
d=""
for i in s1:
  if i not in d:
    d+=i
print(d)




In [ ]:
#Remove Vowels from String using for Loop
s1="asdfghwertypoiuyui"
l=""
for i in s1:
  if i not in ("aeiou"):
    l+=i
print(l)


sdfghwrtypy


In [ ]:


      n = int(input().strip())

      if n==n%2!=0:
          print("Weird")
      for n in range(2,6):
          if n==n%2==0:
              print("Not Weird")
              break
      for n in range(6,21):
          if n==n%2==0:
              print("Weird")
              break
      if n>20 and n==n%2==0:
          print("Not Weird")


IndentationError: ignored

In [ ]:

n=int(input("enetr no of string "))

mylist=[]

for i in range(no_of_string):
  mystring=input()
  mylist.append(int(mystring))

print(mylist)

enetr no of string 3
2
3

['2', '3', '']


In [ ]:
import numpy as np
import numpy as np
n=int(input("enter a no"))
mylist=[]
for i in range(n):
    myno=(input())
    mylist.append(int(myno))

print(np.zeros((mylist)))
print(np.ones((mylist)))



enter a no3
3
3
3
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
n=int(input("enetr no of string "))

mylist=[]

for i in range(n):
  mystring=input()
  mylist.append(int(mystring))
  # print(type(s))
print((sorted(set(mylist))))


enetr no of string 2
4
5
[4, 5]


In [ ]:

#very imp  ### multiple input in the form of int###

arr = map(str, input().split())
print(list(arr))



1
['1']


In [ ]:
## add two list
a=[1,2,3,4,5,6]
b=[9,8,7,4,5,6]
c=[0,0,0,0,0,0]
for i in range(len(a)):
  c[i]=a[i]+b[i]
print(c)



[10, 10, 10, 8, 10, 12]


In [ ]:
## add two list

a=[1,4,3,2,3,4]
b=[3,6,5,4,8]
c=[]
for i,j in zip(a,b):
  z=i+j
  c.append(z)
print(c)

[4, 10, 8, 6, 11]


In [ ]:
#iterables
lst=[1,2,3,4,5,6]
for i in lst:
  print(i)

1
2
3
4
5
6


In [ ]:
### iterator
lst=[1,2,3,4,5,6]
i=iter(lst)
#----------------------------------
next(i) #--->gives 1
#----------------------------------
next(i) #--->gives 2
#----------------------------------
next(i) #--->gives 3
#----------------------------------
next(i) #--->gives 4
#----------------------------------
next(i) #--->gives 5
#----------------------------------
next(i) #--->gives 6

6

In [ ]:
## GENARATOR

def gen(n):
  for i in range (n):
    yield i**2



a=gen(5)
next(a)
next(a)
next(a)
next(a)
next(a)


16

In [ ]:
#DECORATORS

def deco(a,b):
  return a/b

def smart_deco(func):
  def inner(a,b):
    if a<b:
      a,b=b,a
    return func(a,b)
  return inner

deco= smart_deco(deco)

print(deco)



<function smart_deco.<locals>.inner at 0x7fa095a22e60>


In [ ]:


## creating class and objects

class Email:
  pass

e1=Email()

e2=Email()
print(type(e1))

<class '__main__.Email'>


In [ ]:
## class constructor

class emp:
  def __init__(self):   #NON PARAMETERIZED CONSTRUCTION
    self.salary=20000
    self.name="ashutosh"

e1=emp()
e2=emp()
print(e1.__dict__)
print(e2.__dict__)

### PARAMETERIZED CONSTRUCTOR
class emp:
  def __init__(self,sal,name):
    self.salary=sal
    self.name=name

e1=emp(20000,"ashutosh")
e2=emp(25000,"bhushan")
print(e1.__dict__)






{'salary': 20000, 'name': 'ashutosh'}
{'salary': 20000, 'name': 'ashutosh'}
{'salary': 20000, 'name': 'ashutosh'}


In [ ]:
class emp:
  def __init__(self,sal,ag):
    self.salary=sal
    self.age=ag

  def display(self):
    print(f"sa lary of emo is {e1.salary} and age is {e1.age}")



e1=emp(240000,24)
e2=emp(370000,29)
## accessing the atributes
print(e1.salary)# ---> 240000
print(e2.age)

e1.salary=340000
print(e1.salary)# ------> 3400000 ## updating new value

## accessing methods of class
e1.display()

240000
29
340000
slary of emo is 340000 and age is 24


In [ ]:
#### getaatr == setattr == hasattr
class emp:
  def __init__(self,sal,name):
    self.salary=sal
    self.name=name

e1=emp(20000,"ashutosh")
e2=emp(25000,"bhushan")
print(getattr(e1,"salary"))#-----> 200000
setattr(e2,"name","jay")### setting name of emp
print(e2.__dict__)## gives name

print(hasattr(e1,"name"))# --------> hasaatr give is it available --> true or false


20000
{'salary': 25000, 'name': 'jay'}
True


## "isinstance" is a method to check wether the object is a object of perticular class or not

In [ ]:
class emp:
  college_name="CDAC" ### CLASS VARIABLE
  def __init__(self,name,ag):
    self.name=name
    self.age=ag

e1=emp("bhushan",23)
e2=emp("saurabh",22)
print(emp.college_name) # ACCESSING CLASS VARIABLE

emp.college_name="tcs" # updating class variables
print(emp.college_name)



CDAC
tcs


In [ ]:
## setter and getattr methods

class emp:
  def setname(self,name):  ## setter method
    self.name=name

  def getname(self):
    print(self.name)  # getter method
e1=emp()
e2=emp()               # object creation

e1.setname("ram")
e2.setname("sauarabh")    ## setting names

print(e1.__dict__)        ## getting names
print(e2.__dict__)

e1.getname()
e2.getname()

{'name': 'ram'}
{'name': 'sauarabh'}
ram
sauarabh


In [ ]:
## static methods

class bank:
  bank_name="BOI"
  r=12.5
  @staticmethod
  def simple_interst(p,n):
    si=(p*n*r)/100


bank.simple_interst(1000,2)

NameError: ignored

In [ ]:
#INHERITENCE


#without inheritance
class emp:
  bonus=2000
  def display(self):
    print("this is emp class method")

class manager:
  bonus1=5000
  def show(self):
    print("this is manager class method")

e1=emp()
m1=manager()

e1.display()
m1.show()

e1.bonus
m1.bonus1

#############################################################3

#with inheritance

class emp:
  bonus=2000
  def display(self):
    print("this is emp class method")

class manager(emp):
  bonus1=5000
  def show(self):
    print("this is manager class method")

e1=emp()
m1=manager()

m1.bonus  ##3 inheritance achieved # accessing emp by manager object



In [ ]:
class father:
  vehicle1="scooter"
  house1="1 rk"

  def display(self):
    print("this is father class")

class son(father):
    vehicle="BMW"
    house="3 bhk"

    def show(self):
      print("this is son method ")


f1=father()
s1=son()

s1.display()
s1.vehicle1     # accesing method and attributes of parent class
s1.house1



In [ ]:
str="ashuashupatil"
a1=[]
for i in str:
  a1.append(i)

a2=set(a1)

for i in a2:
  print(i,"===>",a1.count(i))



In [ ]:
#PRINT RANGE OF PRIME NO:250 to 350

lower =250
upper=270

for num in range (lower ,upper+1):
  if num>1:
    for i in range(2,num):
      if num%i==0:
        break
      else:
        print(num)
        break


In [ ]:
a=[1,2,5,6,4,5,1,1,1,1,2,2,2,5,5,5,8,8,8,6,6,6,4,4,4]
target=4
b=set(a)
c=[]
for i in b:
  if a.count(i)>=target:
    c.append(i)
print(c)


In [ ]:
for i in range(1,5,1):
  print("*"*i)

In [ ]:
#perfect no
no=int(input())
org=no
sum=0
for i in range(1,no):
  if no%i==0:
    sum=sum+i
if sum==org:
  print("perfect")
else:
  print("not perfect")

In [ ]:
no=1234
sum=0
while no>0:
  rem=no%10
  sum=sum+rem
  no=no//10
print(sum)

In [ ]:
#Find Sum of Squares of Digits of a Number

no=int(input())
order=2
sum=0
while no>0:
  digit=no%10
  sum+=digit**order
  no=no//10
print(sum)


In [ ]:
######    SUPER IN OOPS
# Parent Class
class Vehicle:
  def __init__(self, company, model, year, color):
    self.company = company
    self.model = model
    self.year = year
    self.color = color

# Child Class
class Car(Vehicle):
  def __init__(self, company, model, year, color, car_type):
    # Using super to access __init__ method of Parent Class
    super().__init__(company, model, year, color)
    self.car_type = car_type

# Creating an object of Car
my_car = Car("Tesla", "S", 2021, "Silver", "Sedan")
print(f"I have a {my_car.company} model {my_car.car_type}")

In [ ]:
from os import name
### MULTI-LEVEL INHERITANCE

class human:
  def __init__(self):
    print("in human class")
    self.name="akash"

class emp(human):
  def __init__(self):
    super().__init__()

    print("in class emp")
    self.salary=15000

class manager(emp):
  def __init__(self):
    super().__init__()
    self.bonus=500





m1=manager()
# print(m1.bonus)
########################
e1=emp()
# print(e1.salary)
#####################3
h1=human()
# print(h1.name)
##################################################################
#m1.salary
# e1.name
m1.salary,m1.name,m1.bonus


In [ ]:
## MULTILVEL INHERITANCE
class person:
  def __init__(self,name,age):
    self.name=name
    self.age=age

  def dispaly(self):
    print("person class excuted")

class emp(person):
  def __init__(self,name,age,salary):
    super().__init__(name,age)
    self.salary=salary



class student (person):
  def __init__(self,name,age,marks):
    super().__init__(name,age)
    self.marks=marks
########################################
s1=student('ram',21,50)
print(s1.__dict__)

########################################
e1=emp('sham',24,15000)
print(e1.__dict__)

########################################

s1.dispaly()
e1.dispaly
#######################################

In [ ]:
##ENCAPSULATION

class emp:
  def __init__(self,name,salary):
    self.___name=name
    self.__salary=salary

  def display(self):
    print(f"name is{self.__name} and salary is{self.__salary}")


e1=emp("sham",510000)
print(e1.__dict__)


In [ ]:
# ENCAPSULATION ACHIEVED
class finance:
  def __init__(self):
    self.__revenue=1000000  #private data
    self.sales=135

  def display(self):
     print(f"revenue is {self.__revenue}")


class hr:
  def __init__(self):
    self.no_emp=32

h1=hr()
print(h1.__dict__)

# f1.revenue  #-------------> class finance does not have attribute like revenue
                            # its become strong private so not visisble

# f1.__revenue # ------------> also unable to print this

## so to access the str private element we add other function to display it
f1=finance()

f1.display()


{'no_emp': 32}
revenue is 1000000


In [ ]:
## POLYMORPHISM

EMP=["RAM","SHAM","SOPAN","NAMU"]
COMPANY="PADMINIGROUP"

for i in  reversed(EMP):
  print(i)

print("##################")

for i in  reversed(COMPANY):  ## reversed can play difernt role in each role
  print(i)

##############  or ##############3
a=20
b=50
print(a+b)

a="ram"
b="sita"   #  here  "+" oprerator play different role addition
                        #for one and concatination for other
print(a+b)

NAMU
SOPAN
SHAM
RAM
##################
P
U
O
R
G
I
N
I
M
D
A
P
70
ramsita


In [ ]:
## OVERRIDING / OPERATOR OVERRIDING
class cart:
  def __init__(self,bas1,bas2,bas3):
    self.clothes=bas1
    self.electronic=bas2
    self.other=bas3
  def __len__(self):
    print("total no. of items")
    return len(self.clothes)+len( self.electronic)+len(self.other)



ram=cart(["pant","shirt","t-shirt"],["earphone","mobile"],["chair","brush"])
print(len(ram))  # gives error but we want ans=6,so we use magic method



total no. of items
7


In [ ]:
## OPERATOR OVERLOADING

class book:
  def __init__(self,title,pages):
    self.title=title
    self.pages=pages

  def __add__(self,other):
    total=self.pages+other.pages
    return total





b1=book("one indian girl",300)
b2=book("half girlfriend",200)


print(b1+b2)






500


In [ ]:
# ABSTRACTION

#note:= we can not create an object of abstarct class

from abc import ABC ,abstractmethod

class car(ABC):
  @abstractmethod
  def milage(self):
    pass

  def color(self):
    print("white")


class maruti_suzuki(car):
  def milage(self):
    print("milage is 30kmph")

class tata(car):
  def milage(self):
    print("milage is 35kmph")

class mahindra(car):
  def milage(self):
    print("milage is 40kmph")


ms1=maruti_suzuki()
t1=tata()                 ## created objects
m1=mahindra()

###############################################
ms1.milage()
t1.milage()
m1.milage()
###################################################

ms1.color()
t1.color()
m1.color()


milage is 30kmph
milage is 35kmph
milage is 40kmph
white
white
white


In [ ]:
no=int(input("enter a no"))

if no%2!=0:
  print("weird")

else:
  if no%2==0 and no>=6 and no<=20:
    print(" weird")

  elif no%2==0 and no>20:
    print("not weird")

  elif no%2==0 and no>=2 and no<=5:
    print("not wierd")



In [ ]:
no=(input())
l=[]
for i in no:
  l.append(i)
lst=list(map(int,l))
# lst=[1,9,8,7]
a1=sorted(lst)
a2=a1[::-1]



In [ ]:
a=["1","5","7"]
a1=(list(map(int,a)))

In [ ]:
no=(input())
l=[]
min_num=[]
for i in no:
  l.append(i)

l.sort()
for i in l:
  min_num.append(i)

max_num=min_num[::-1]

final_min=int("".join(min_num))
final_max=int("".join(max_num))

diff=final_max-final_min
print(diff)

In [ ]:
a=[]
no=input()
for i in no:
  a.append(i)
a1=sorted(a)
min_no=int("".join(a1))
a2=a1[::-1]
max_no=int("".join(a2))
diff=max_no-min_no

print(diff)


In [ ]:
def mutate_str(s,i,ch):
  a=s.replace(s[i],ch)

  print(a)

s=input("enter a string")
i,ch=input().split()
str_new=mutate_str(s,int(i),ch)




In [ ]:
a=[]
def mutate_str(s,i,c):
  for x in s:
    a.append(x)
a1=a.insert(4,c)
a2=" ".join(a)
print(a2)


s=input("enter a string")
i,c=input().split()
str_new=mutate_str(s,int(i),c)

In [ ]:
n=input()
list1=n.split(' ')
for i in list1:
     print(i.capitalize(),end=" ")















In [ ]:
#B A N A N A

s="banana"
a=s.startswith("a")
print(a)






In [ ]:
# write code for all possible no which gives sum of 30

lst=[1,2,3,4,5,6,7,8,9,10,2,5,8,9,4]
target=15

for i in range(len(lst)):
  for j in range(i,len(lst)):
    if (lst[i]+lst[j]==target):
        print(lst[i],lst[j])



In [ ]:
## 3 possible no which gives sum 30
lst=[1,2,3,4,5,6,7,8,9,10,2,5,8,9,4]
target=30

for i in range(len(lst)):
  for j in range(i,len(lst)):
    for k in range(i,j,len(lst)):
      if(lst[i]+lst[j]+lst[k]==target):
          print(lst[i],lst[j],lst[k])



In [ ]:
#find 3rd max no from array without using sort
lst=[1,2,3,4,5,6,7,8,9,10,2,5,8,9,4]

lst1=set(lst)

lst_max=max(lst1)
lst1.remove(lst_max)

lst_secd_max=max(lst1)
lst1.remove(lst_secd_max)

lst_third_max=max(lst1)
print(lst_third_max)

In [ ]:
def is_palindrome(s):
    return s == s[::-1]

def check_palindrome_substring(string, start, end):
    substring = string[start:end+1]
    return is_palindrome(substring)


string = "aaabbaaa samas "
start = 3
end = 6
result = check_palindrome_substring(string, start, end)
print(result)

In [ ]:
from collections import Counter

def count_anagrams(words, word):
    word_count = Counter(word)
    count = 0
    for w in words:
        if Counter(w) == word_count:
            count += 1
    return count

words = [ "dog","tam","ring"]
word = "god"
count = count_anagrams(words, word)
print(count)  # Output: 1


In [ ]:
l=[10,8,4,2,1,6]
x=len(l)
for i in range(x):
  for j in range(i+1,x):
    if l[i]>l[j]:
      l[i],l[j]=l[j],l[i]

print(l)


In [ ]:
def romanToInt(s):
    d = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
    ans=0
    for i in range(len(s)):
      if i+1!=len(S) and d[s[i]]<d[s[i+1]]:
        ans=ans-d[s[i]]
      else:
        ans=ans+d[s[i]]
    print(ans)

S="IXXI"
romanToInt(S)


In [ ]:
S="IXXI"
d = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}

for i in range(len(S)):
  if i+1!=len(S) and d[s[i]]<d[s[i+1]]:
            ans=ans-d[s[i]]
  else:
                ans=ans+d[s[i]]








In [ ]:
def romanToInt(s):


        d = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
        ans=0
        for i in range(len(s)):
          if i+1!=len(s) and d[s[i]]<d[s[i+1]]:
            ans=ans-d[s[i]]
          else:
            ans=ans+d[s[i]]
        print(ans)

s=input()
romanToInt(s)

In [ ]:
arr = list(map(str, input().split()))
print((arr))
print(type(arr))

dfghjk
['dfghjk']
<class 'list'>


In [ ]:
str=input("enter a str")
s1=list(sorted(set(str.split(','))))
s2=list(str)
for i in s1:
  print(i,"--->",s2.count(i))


In [ ]:
s1={120,5,45,84,840,120,5,4,45}
a=set(s1)
a

In [ ]:
l=[]
s='omkar'
for i in s:
  l.append(i)

l



In [ ]:
s='omkar'
s1=list(s)
print(s1)

In [ ]:
#a=[3a,4b,5c,1d] expected o\p aaabbbbcccccd
a = ['3a', '4b', '5c', '1d']
result = ''
for elem in a:
    result += elem[-1] * int(elem[:-1])
print(result)






In [ ]:
a = ['3a', '4b', '5c', '1d']
res=''
for i in a:
  res+=i[-1]*int(i[:-1])
print(res)

In [ ]:
d=1,
a) a=1,2,3
b) b=(1,2,3)
c) c=(1)
d) d=1,
print(type(d))

In [ ]:
d=(1)
print(type(d))

In [ ]:
st='ashutosh ghodke'
s1=st.split()
print(s1.reverse())

In [ ]:
import datetime
now = datetime.datetime.now()
print ("Current date and time : ")
print (now.strftime("%Y-%m-%d %H:%M:%S"))


In [ ]:
import sys
print(sys.version)

In [ ]:
rad=eval(input())
area=3.14*(rad**2)
area


In [ ]:
from math import pi
rad=eval(input())
area=pi * rad**2
area

In [ ]:
fname=input()
lname=input()
fname,lname=lname,fname
print(fname,' ',lname)

In [ ]:

lst=[11,22,33,44,1,850]
# max=lst[0]
# for i in lst:
#   if i>max:
#     max=i
# print(max)

# --- or---
# print(max(lst))

# --- or---

# print(lst[-1])

In [ ]:
s1=list(map(str,input().split()))
print(s1)

s2=tuple(map(str,input().split()))
print(s2)





In [ ]:
N1=STR(INPUT())
N2=N1.SPLIT()
PRINT(N2[-1])

In [ ]:
n1=input()
n2=n1.split('.')
print(n2[-1])

In [ ]:
color_list = ["Red","Green","White" ,"Black"]
print(color_list[0])
print(color_list[-1])

In [ ]:
exam_st_date = (11, 12, 2014)
print("%i / %i / %i" %exam_st_date )


In [ ]:
#write a python program to count the frequency of words
# Appering in a string

def count():
  str=input("enter a str")
  s1=sorted(set(str.split()))
  s2=str.split()

  for i in s1:
    print(i,"--->",s2.count(i))


In [ ]:
s2=[]
s1='niranjan'
for i in s1:
  s2.append(i)

s3=set(s2)

for i in s3:
  print(i,'---->',s2.count(i))


In [ ]:
#a2 b3 c4

lst=[]
s='a2b3c4d'
for i in s:
  lst.append(i)
p=lst[0]*int(lst[1])
q=lst[2]*int(lst[3])
r=lst[4]*int(lst[5])
print(p,q,r)

In [ ]:
import pyspark

if __name__ == "__main__":
	sc=pyspark.SparkContext()
	rdd=sc.parallelize(['hello','world'])
	words=sorted(rdd.collect())
	print(words)


In [ ]:
#. Create a function that takes a list of integers and returns the largest and smallest integers in the list.


def abc(lst):
  print(max(lst))
  print(min(lst))

lst=[1,2,3,4,5,6]
abc(lst)



In [ ]:
# #3. Write a program to sort a list without using sort and sorted(in built function) and find the second largest number in a list.
# # a= [ 5,2,7,8,1,3,8,9,13]

# a = [5, 2, 7, 8, 1, 3, 8, 9, 13]
# max_num = a[0]
# second_max =a[0]

# for i in a:
#     if i > max_num:
#         second_max = max_num
#         max_num = i
#     elif i > second_max and i < max_num:
#         second_max = i

# print("Second largest number in the list:", second_max)


In [ ]:
#1.	Python program to add two numbers
num1=int(input())
num2=int(input())
print(num1+num2)


In [ ]:
#2.	Maximum of two numbers in Python
num1=int(input())
num2=int(input())
if num1>num2:
  print(num1)
else:
  print(num2)


In [ ]:
#3.	Python Program for factorial of a number
def fact(num):
  if num==1:
    return 1

  else:
    return num*fact(num-1)


fact(4)

In [ ]:
#4.	Python Program for simple interest
si=0
p=1000
n=3
r=20
si=(p*n*r)/100
print(si)


In [ ]:
#16.	Python program to interchange first and last elements in a list

l=[12,13,14,15,16,17,10]
k=l.pop(0)
l.append(k)

p=l.pop(-2)
l.insert(0,p)
l
#  ------------------ or ------------------

#  a=[10,20,30,40]
# a[0],a[3]=a[3],a[0]
# a

In [ ]:
# 17.	Python program to swap two elements in a list

a=[10,20]
a[0],a[1]=a[1],a[0]
print(a[0],a[1])

In [ ]:
# 18.	Python | Ways to find length of list

# a=[10,20,30,40]
# b=[]
# len=0
# print(len(a))
# -------------------------------
# for i in a:
#   b.append(i)
#   len+=1
# len
# ---------------------------------
# count=0
# for _ in a:
#   count+=1
# count

In [ ]:
###19.	Python | Ways to check if element exists in list
l = [1, 2, 3, 4, 5]
i=int(input())
if i in l:
  print('yes')
else:
  print('no')

----------------------------------
my_list = [1, 2, 3, 4, 5]
element = 3
for item in my_list:
    if item == element:
        print("Element exists in the list")
        break
else:
    print("Element does not exist in the list")


In [ ]:
# # 20.	Different ways to clear a list in Python
# my_list = [1, 2, 3, 4, 5]
# my_list.clear()
# print(f"{my_list}")
# -----------------------------------
# my_list = [1, 2, 3, 4, 5]
# del my_list[:]
# print(f"Cleared list:{ my_list}")


# ---------------------------------
# l=[10,20,30,50,55,22]
# l=[]
# l
# =====================================
# l=[10,20,30,50,55,22]
# for i in range (len(l)-1,-1,-1):
#   l.pop(i)

# l
# =====================================

# l=[10,20,30,50,55,22]
# for i in l.copy():
#   l.remove(i)
# l

# =========================================






In [ ]:
# 21.	Python | Reversing a List
# l=[10,20,30,50,55,22]
# l.reverse()
# l

# l=[10,20,30,50,55,22]
# k=l[::-1]
# k

# l=[10,20,30,50,55,22]
# rev=[]
# for i in range(len(l)-1,-1,-1):
#   rev.append(l[i])
# rev


# l=[10,20,30,50,55,22]
# h=list(reversed(l))
# h

# l=[10,20,30,50,55,22]
# rev=[]
# while l:
#   rev.append(l.pop())
# rev


In [ ]:
l1=[10,20,30]
l2=[40,50,60]
l3=[]
i=0
for i in range(len(l1)):
  op=l1[i]+l2[i]
  l3.append(op)
l3


In [ ]:
d='ashutosh'
g=[]
for i in d:
  g.append(i)
for i in range(len(g)):
  print(f"{i}---->{g[i]}")


In [ ]:
a='rushikesh'
for k,v in enumerate(a):
  print(k,'-->',v)

In [ ]:
# 23.	Python | Multiply all numbers in the list

l=[1,2,3,4,5]
res=1
for i in l:
  res*=i
print(res)

In [ ]:
# 24.	Python program to find smallest number in a list
l=[10,20,30,50,55,22]
min=l[0]
for i in l:
  if i<min:
    min=i
print(min)

# =================================

# my_list = [5, 3, 9, 1, 7]
# smallest_number = min(my_list)
# print(smallest_number)

# =================================



In [ ]:
# # 25.	Python program to find largest number in a list

l=[10,20,30,50,55,22]
max=l[0]
for i in l:
  if i>max:
    max=i
print(max)

# =====================================


# l=[10,20,30,50,55,22]
# print(max(l))
# ===============================

l = [10, 20, 30, 50, 55, 22]
unique_nums = set(l)
sorted_nums = sorted(unique_nums)
largest=sorted_nums[-1]
print(largest)



In [ ]:
# # 26.	Python program to find second largest number in a list

# l = [10, 20, 30, 50, 55, 22]
# max_num = l[0]
# second_max = l[0]

# for num in l:
#     if num > max_num:
#         second_max = max_num
#         max_num = num
#     elif num > second_max and num < max_num:
#         second_max = num

# print(second_max)


# =================================

l = [10, 20, 30, 50, 55, 22]
unique_nums = set(l)
sorted_nums = sorted(unique_nums)
second_largest = sorted_nums[-2]

print(second_largest)


In [ ]:
# 27.	Python program to find N largest elements from a list

def find_n_largest_elements(numbers, N):
    if N <= 0 or len(numbers) == 0:
        return []

    numbers.sort(reverse=True)
    return numbers[:N]

#
my_list = [10, 30, 20, 50, 40, 60, 70]
N = 3
n_largest_elements = find_n_largest_elements(my_list, N)
print(n_largest_elements)


In [ ]:
# 6) Reverse string by loop

g="ashu"
k=[]
for i in g:
  k.append(i)
k[::-1]

In [ ]:
# 7) In a list there is a string, print 5 times that string into list
g=['ashu']
m=g*5
m

In [ ]:
# input="komal"
# # output=k-o-m-a-l

# strr=(input())
# l=[]
# for i in strr:
#   l.append(i)
# for i in l:
#   print(i+('-'),end=" ")

# --------------------------
input_string = input("Enter a string: ")  # Prompt the user for input

output_string = "-".join([x for x in input_string])

print(output_string)


In [ ]:
abc="komal"
123="komal"
print(abc)
print(123)

In [ ]:
l=[10,20,30]
m=[2,5,8]

for a,b in zip(l,m):
  print(a,b)

In [ ]:
# shalliow and deep copy
import copy

l=[10,20,30,[10,20]]
l_copy=copy.copy(l)

l_copy[1]=50
l_copy[3].append(100)
print((l))
print((l_copy))


[10, 20, 30, [10, 20, 100]]
[10, 50, 30, [10, 20, 100]]


In [ ]:
import copy

l=[10,20,30,[10,20]]
l_copy=copy.deepcopy(l)

l_copy[1]=50
l_copy[3].append(100)
print((l))
print((l_copy))


[10, 20, 30, [10, 20]]
[10, 50, 30, [10, 20, 100]]


In [ ]:
strr='ashutosh'
# for i,x in enumerate(strr):
#   print(i,'==',x)

# or

for i in range(len(strr)):
  print(i,'=',strr[i])

In [ ]:
s={10,20,30}
# print(type(s))
s.add(80)
s

In [ ]:
strr='ashutosh'
for i in range(len(strr)-1,-1,-1):
  print(strr[i],end='')

In [ ]:
s='ashutosh'
str(s[::-1])

In [ ]:
s = 'ashutosh'
output = str(s[::-1]).replace(' ',)
print(output)


In [ ]:
# input=aaabbc
#output= 3a2b1c
from itertools import groupby

input_str = 'aaabbc'
result = ""
for char, group in groupby(string):
        count = len(list(group))
        result += str(count) + char









Output: 3a2b1c


In [ ]:
#decorator

def uppercase_decorator(func):
    def wrapper():
        return func().upper()
    return wrapper

@uppercase_decorator
def func():
    return "hello"

# Test the decorated function
greeting = func()
print(greeting)


HELLO


In [ ]:
v='decoratorc'
for i in range(len(v)-1,-1,-1):
  print(v[i],end='')



crotaroced

In [ ]:
v=['decoratorc']
h=v*5
h

['decoratorc', 'decoratorc', 'decoratorc', 'decoratorc', 'decoratorc']

In [ ]:
def upper_deco(func):
  def wrapper():
    return func().upper()
  return wrapper


@upper_deco
def func():
  return 'hello sir'

greet=func()
print(greet)

HELLO SIR


In [ ]:
i=[1,2,5,3,5,2,8]
lst=iter(i)
next(lst)
next(lst)
next(lst)    ### iterator
next(lst)


3

In [ ]:
def gen(n):
  for i in range (n):
    yield i**2


a=gen(5)     ### generator
next(a)
next(a)
next(a)
next(a)

9

In [ ]:
## class constructor

class emp:
  def __init__(self):   #NON PARAMETERIZED CONSTRUCTION
    self.salary=20000
    self.name="ashutosh"

e1=emp()
e2=emp()
print(e1.__dict__)
print(e2.__dict__)

{'salary': 20000, 'name': 'ashutosh'}
{'salary': 20000, 'name': 'ashutosh'}


In [ ]:
class emp:
  def __init__(self,sal,name):
    self._salary=sal
    self.__name=name
e1=emp(20000,'ashu')
e2=emp(50000,'bhushu')
e3=emp(70000,'sauru')


print(e1.__dict__)
print(e2.__dict__)
print(e3.__dict__)

{'_salary': 20000, '_emp__name': 'ashu'}
{'_salary': 50000, '_emp__name': 'bhushu'}
{'_salary': 70000, '_emp__name': 'sauru'}


In [ ]:
class emp:
  bonus=2000
  def display(self):
    print('this is parent class')

class manager():
  bonus=5000
  def show(self):
    print('this is a child class ')

e1=emp()
m1=manager()
e1.bonus
m1.bonus

5000

In [ ]:
class emp:
  bonus=2000
  def display(self):
    print('this is parent class')

class manager(emp):
  bonus=5000
  def show(self):
    print('this is a child class')

e1=emp()
m1=manager()

m1.display()
m1.show()

this is parent class
this is a child class


In [ ]:
# ENCAPSULATION ACHIEVED
class finance:
  def __init__(self):
    self.__revenue=1000000  #private data
    self.sales=135

  def display(self):
     print(f"revenue is {self.__revenue}")

class hr:
  def __init__(self):
    self.emp_no=800

h1=hr()
f1=finance()

print(h1.__dict__)

f1.sales
f1=finance()

f1.display()

{'emp_no': 800}
revenue is 1000000


In [ ]:
 # ENCAPSULATION ACHIEVED
class finance:
  def __init__(self):
    self.__revenue=1000000  #private data
    self.sales=135

  def display(self):
     print(f"revenue is {self.__revenue}")


class hr:
  def __init__(self):
    self.no_emp=32

h1=hr()
print(h1.__dict__)

# f1.revenue  #-------------> class finance does not have attribute like revenue
                            # its become strong private so not visisble

# f1.__revenue # ------------> also unable to print this

## so to access the str private element we add other function to display it
f1=finance()

f1.display()


{'no_emp': 32}
revenue is 1000000


In [ ]:
## abstraction
#note:= we can not create an object of abstarct class

from abc import ABC,abstractmethod

class car(ABC):
  @abstractmethod
  def milage(self):
    pass

  def colour(self):
    print('white')

class maruti_suzuki(car):
  def milage(self):
    print('milage is 30kmph')

  def colour(self):
      print('PURPLE')

class tata(car):
  def milage(self):
    print('milage is 40kmph')

  def colour(self):
      print('RED')

class mahindra (car):
  def milage(self):
    print('milage is 50kmph')

  def colour(self):
    print('YELLOW')

m1=maruti_suzuki()
t1=tata()
mahi=mahindra()


# m1.milage()   #-----> milage is 30 kmph

# t1.milage()     #---->milage is 40 kmph

# mahi.milage()    #---->milage is 50 kmph

#====================================================##==============###

m1.colour()      #----> WHITE
t1.colour()      #----> WHITE
mahi.colour()    #----> WHITE

PURPLE
RED
YELLOW


In [ ]:
def fact(n):
  if n==0:
    return 1
  else:
    return n*fact(n-1)
fact(5)

120

In [ ]:
s=lambda x:x*x
print(s(4))

16


In [ ]:
c=lambda x,y:x+y
print(c(5,6))

11


In [ ]:
s=lambda x,y:x if x>y else y
s(100,20)

100

In [ ]:
# ## filter / map / reduce
# ## FILTER :->
# ## even no
# # a=[1,2,3,4,5,6,7,8,9,10]
# # v=list(filter(lambda x:x%2==0,a))
# # v

# ## odd no

# # a=[1,2,3,4,5,6,7,8,9,10]
# # c=list(filter(lambda x: x%2!=0,a))
# # c


# note:==>  FOR FILTER THERE IS MINIMUM OUTPUT FOR THE GIVEN INPUT LIKE
#        IF INPUT=[1,2,3,4,5,6]  -> 6
#           OUTPUT [2,4,6] -->3


[1, 3, 5, 7, 9]

In [ ]:
# ## REDUCE

# from functools import *
# s=[10,20,30,40,54,80,60]
# g=(reduce(lambda x,y:x+y,s))
# g



# note:==>  FOR REDUCE THERE IS EXACT ONE NO OF  OUTPUT FOR THE GIVEN INPUT LIKE
#        IF INPUT=[1,2,3,4,5,6]  -> 6
#           OUTPUT [21] -->6


294

In [ ]:
# with open
f=open('Spark.txt_IMP_BHUSHAN.txt','w')
print(f.name)
print(f.mode)
print(f.closed)
f.close()
print(f.closed)



Spark.txt_IMP_BHUSHAN.txt
w
False
True


In [ ]:
#with open as

with open ('Spark.txt_IMP_BHUSHAN.txt','w') as op:
  print(f.name)
  print(f.mode)
  print(f.writable())
  # print(f.readable())


  # print(f.closed) #====> auto closer .
  # f.close()
  # print(f.closed)
  # print(f.readable())




Spark.txt_IMP_BHUSHAN.txt
w


ValueError: ignored

In [ ]:
with open ('sandy.txt','w')as wp:
  wp.write('ashutosh ghodke')
  print('writing operation is completed ')


### now reading

with open('sandy.txt','r')as red:
  print(red.readline())


writing operation is completed 
ashutosh ghodke


In [ ]:
## for iterable #write operation

lst=[10,20,30,'ashu','maya','sandy']
tup=('sauru','pravin',1,2)
sett={'abc','sfr',50,60}
dictt={'maya':'baby','love':'ashu'}


with open('sandy1.txt','w') as wp:
  wp.writelines(str(lst))
  wp.writelines(str(lst))
  wp.writelines(str(tup))
  wp.writelines(str(sett))
  wp.writelines(str(dictt))

o=open('sandy1.txt','r')
print(o.read())




[10, 20, 30, 'ashu', 'maya', 'sandy'][10, 20, 30, 'ashu', 'maya', 'sandy']('sauru', 'pravin', 1, 2){50, 60, 'abc', 'sfr'}{'maya': 'baby', 'love': 'ashu'}


In [ ]:
o=open('sandy1.txt','r')
print(o.read())
x=[]
for i in o:







[10, 20, 30, 'ashu', 'maya', 'sandy'][10, 20, 30, 'ashu', 'maya', 'sandy']('sauru', 'pravin', 1, 2){50, 60, 'abc', 'sfr'}{'maya': 'baby', 'love': 'ashu'}


In [ ]:
s='komal'
k=[]
for i in s:
  k.append(i)
y='-'.join(k)
y

'k-o-m-a-l'

In [ ]:
lst=[55,44,99,88,22,11,66]
sorted(lst,reverse=True)


[99, 88, 66, 55, 44, 22, 11]

In [ ]:
lst=[55,44,99,88,22,11,66]
print(lst[1:3:1])

[44, 99]


In [ ]:
lst=[55,44,99,88,22,11,66]
print(lst[::-2])


[66, 22, 99, 55]


In [ ]:
lst=[55,44,99,88,22,11,66]
sum(lst)
max(lst)
min(lst)
# print(sorted(lst))


11

In [ ]:
lst=[55,44,99,88,22,11,66]
lst.append([100,200,300])
lst

[55, 44, 99, 88, 22, 11, 66, [100, 200, 300]]

In [ ]:
lst=[55,44,99,88,22,11,66]
lst.append(100)
lst

[55, 44, 99, 88, 22, 11, 66, 100]

In [ ]:
lst=[55,44,99,88,22,11,66]
lst.extend([10,20,3])
lst

[55, 44, 99, 88, 22, 11, 66, 10, 20, 3]

In [ ]:
lst=[55,44,99,88,22,11,66]
lst.insert(2,100)
lst

[55, 44, 100, 99, 88, 22, 11, 66]

In [ ]:
lst=[55,44,99,88,22,11,66]
lst.insert(0,5000)
lst

[5000, 55, 44, 99, 88, 22, 11, 66]

In [ ]:
lst=[55,44,99,88,22,11,66]
lst.insert(-1,6000)
lst

[55, 44, 99, 88, 22, 11, 6000, 66]

In [ ]:
lst=[55,44,99,88,22,11,66]
lst.insert(50,8000)
lst

[55, 44, 99, 88, 22, 11, 66, 8000]

In [ ]:
lst=[55,44,99,88,22,11,66]
avg(lst)

NameError: ignored

In [ ]:
lst=[55,44,99,88,22,11,66]
lst.insert(-1,8000)
lst

[55, 44, 99, 88, 22, 11, 8000, 66]

In [ ]:
lst=[55,44,99,88,22,11,66]
a=lst[-1]
a

66

In [ ]:
##3 avg < no. in list
lst=[25,34,19,28,22,32,112,111,99]
target=sum(lst)/len(lst)

for i in lst:
  if i < target:
    print(i)



25
34
19
28
22
32


In [ ]:
lst=[25,34,19,28,22,32,112,111,99]
lst.remove(22)
lst

[25, 34, 19, 28, 32, 112, 111, 99]

In [ ]:
lst=[25,34,19,28,22,32,112,111,99]
lst.pop()
lst

[25, 34, 19, 28, 22, 32, 112, 111]

In [ ]:
# komal ====> k-o-m-a-l
g='komal'
'-'.join(g)


'k-o-m-a-l'

In [ ]:
lst=[25,34,19,28,22,32,112,111,99]
# lst[1]
# lst[-2]
# max(lst)
# min(lst)
# sum(lst)
# sorted(lst)
# lst.sort()
# lst

482

In [ ]:
lst=[25,34,19,28,22,32,112,111,99]
lst[3:6:1]
lst[::-1] ## reverse
lst[1::2]  ## start : end : step
lst[:4]

[25, 34, 19, 28]

In [ ]:
lst=[25,34,19,28,22,32,112,111,99]
# lst.append(100)# appending number
# lst
# lst.append([100,200,300])# appending list
# lst
# lst.append((100,200,333)) #appending tuple
# lst
# lst.append({111,222,333}) ## appending set
# lst
lst.append({1:'a',2:'b',3:'c'}) #3 appending dictionary
lst
# lst.append(frozenset[10,200,565]) ## appending frozenset
# lst

[25, 34, 19, 28, 22, 32, 112, 111, 99, {1: 'a', 2: 'b', 3: 'c'}]

In [ ]:
lst=[25,34,19,28,22,32,112,111,99]
# lst.extend([100,200,300])
# lst
# lst.extend((100,200,300))
# lst
# lst.extend({100,5565,333})
# # lst
# lst.extend({1:'a',2:'b',3:'c'})
# lst
# frozen set can not be extended

[25, 34, 19, 28, 22, 32, 112, 111, 99, 1, 2, 3]

In [ ]:
lst=[25,34,19,28,22,32,112,111,99]
lst.insert(3,5000)
lst
lst.insert(5,2000)
lst
lst.insert(0,52525)
lst
lst.insert(-1,85025)## by default last second index
lst
lst.insert(55,98989)## if index is out of range then it places it to last place
lst

[52525, 25, 34, 19, 5000, 28, 2000, 22, 32, 112, 111, 85025, 99, 98989]

In [ ]:
lst=[25,34,19,28,22,32,112,111,99]
lst.remove(111)
lst

[25, 34, 19, 28, 22, 32, 112, 99]

In [ ]:
lst=[25,34,19,28,22,32,112,111,99]
lst.pop(5)
lst
lst.pop()
lst
lst.pop()
lst.clear()
lst

[]

In [ ]:
lst=[25,34,19,28,22,32,112,111,99]
turn=int(input())
for i in range(turn):

  g=lst.pop(0)
  lst.append(g)
  print(lst)
len(lst)

9
[34, 19, 28, 22, 32, 112, 111, 99, 25]
[19, 28, 22, 32, 112, 111, 99, 25, 34]
[28, 22, 32, 112, 111, 99, 25, 34, 19]
[22, 32, 112, 111, 99, 25, 34, 19, 28]
[32, 112, 111, 99, 25, 34, 19, 28, 22]
[112, 111, 99, 25, 34, 19, 28, 22, 32]
[111, 99, 25, 34, 19, 28, 22, 32, 112]
[99, 25, 34, 19, 28, 22, 32, 112, 111]
[25, 34, 19, 28, 22, 32, 112, 111, 99]


9

In [ ]:
lst=[25,34,19,28,22,32,112,111,99]
lst.index(28)

3

In [ ]:
lst=[25,34,19,28,22,22,32,112,111,99]
lst.count(22)
lst.sort()
lst

[19, 22, 22, 25, 28, 32, 34, 99, 111, 112]

In [ ]:
## tuple
tup=(10,20,30,40,50,60,10)
tup.count(10)## count-> gives the occurence of given no in tuple

2

In [ ]:
tup=(10,20,30,40,50,60,10)
tup.index(50)## .index gives the index position of given number

4

In [ ]:
tup=(10,20,30,40,50,60,10)
tup[::-1] ## can be reversed but its temporary

(10, 60, 50, 40, 30, 20, 10)

In [ ]:
#1.	Python program to Find the size of a Tuple
tup=(10,20,30,40,50,60,10)
print(len(tup))

7


In [ ]:
#2.	Python – Maximum and Minimum K elements in Tuple
tup=(10,20,30,40,50,60,10)
max(tup)
min(tup)


10

In [ ]:
#3.	Create a list of tuples from given
#list having number and its cube in each tuple

lst=[10,20,30,40,50,60,10]
tup=[]
for i in lst:
  a=i,'--->',i**3
  tup.append(a)
tup



[(10, '--->', 1000),
 (20, '--->', 8000),
 (30, '--->', 27000),
 (40, '--->', 64000),
 (50, '--->', 125000),
 (60, '--->', 216000),
 (10, '--->', 1000)]

In [ ]:
#4.	Python – Adding Tuple to List and vice – versa
tup=(10,20,30,40,50,60,10)
lst=[]                     ## tuple added in list
lst.extend(tup)
lst

##---------------------
# lst=[10,20,30,40,50,60,10]
# tup=(11,22,33,44,55)                 ## listed added in tuple
# print(tuple(lst+list(tup)))


[10, 20, 30, 40, 50, 60, 10]

In [ ]:
#6.	Python – Join Tuples if similar initial element
tuples = [(1, 'a', 'b'), (2, 'c', 'd'), (1, 'e', 'f'), (3, 'g', 'h')]
joined_tuples = []

for key, *values in tuples:
    if joined_tuples and key == joined_tuples[-1][0]:
        joined_tuples[-1] += values
    else:
        joined_tuples.append((key, *values))

print(joined_tuples)




[(1, 'a', 'b'), (2, 'c', 'd'), (1, 'e', 'f'), (3, 'g', 'h')]


In [ ]:
##7.	Python – Extract digits from Tuple list
lst = [(1, 'abc', 2), ('def', 3, 4), (5, 'ghi', 'jkl')]
digits = []

for tup in lst:
    for item in tup:
        if isinstance(item, int):
            digits.append(item)
digits



[1, 2, 3, 4, 5]

In [ ]:
## remove tuple of length k
lst = [(1, 2), (3, 4, 5), (6,), (7, 8, 9)]
k=2
for i in lst:
  if len(i)==k:
    lst.remove(i)
lst



[(3, 4, 5), (6,), (7, 8, 9)]

In [ ]:
# 10.	Sort a list of tuples by second Item
tuple_list = [(3, 'apple'), (1, 'orange'), (2, 'banana')]

sorted_list = sorted(tuple_list, key=lambda x: x[1])

print(sorted_list)


[(3, 'apple'), (2, 'banana'), (1, 'orange')]


In [ ]:
#11.	Python program to Order Tuples using external List
external_list = ['orange', 'banana', 'apple']
tuple_list = [(3, 'apple'), (1, 'orange'), (2, 'banana')]

sorted_list = sorted(tuple_list, key=lambda x: external_list.index(x[1]))

print(sorted_list)


[(1, 'orange'), (2, 'banana'), (3, 'apple')]


In [ ]:
dic={1:'one',2:'two',3:'three',4:'four',5:'five'}

dic[6]='six'
dic.update({7:'seven'})
dic.pop(7)
dic.keys()
dic.values()
dic.items()
dic.fromkeys([2,3])

{2: None, 3: None}

In [ ]:
#1.	Python – Extract Unique values dictionary values
dic={1:'one',2:'two',3:'three',4:'four',5:'five'}
for i in dic.keys():
  print(i,end=' ')

1 2 3 4 5 

In [ ]:
#2.	Python program to find the sum of all items in a dictionary

dic = {'key1': 10,'key2': 20,'key3': 30,'key4': 40}
add=sum(dic.values())
add

100

In [ ]:
#3.	Python | Ways to remove a key from dictionary

# 1st method
dic = {'key1': 10,'key2': 20,'key3': 30,'key4': 40}
# dic.pop('key2')
# dic

# 2nd method
# dic.popitem() ## last key deleted
# dic

# 3rd method
del dic['key4'] ## 4th key deleted
dic



{'key1': 10, 'key2': 20, 'key3': 30}

In [ ]:
#4.	Ways to sort list of dictionaries by values in Python – Using itemgetter
dic = {'key1': 100,'key2': 80,'key3': 30,'key4': 60}
c=sorted(dic.items())
c


[('key1', 100), ('key2', 80), ('key3', 30), ('key4', 60)]

In [ ]:
# 5.	Ways to sort list of dictionaries by values in Python – Using lambda function
dic = {'key1': 100,'key2': 80,'key3': 30,'key4': 60}
sorted_list = sorted(dic.items(), key=lambda x: x[1])
print(sorted_list)

[('key3', 30), ('key4', 60), ('key2', 80), ('key1', 100)]


In [ ]:
# 6.	Python | Merging two Dictionaries
dict1 = {'key1': 'value1', 'key2': 'value2'}
dict2 = {'key3': 'value3', 'key4': 'value4'}

dict1.update(dict2)

print(dict1)

# or
dict1 = {'key1': 'value1', 'key2': 'value2'}
dict2 = {'key3': 'value3', 'key4': 'value4'}

merged_dict = {**dict1, **dict2}

print(merged_dict)


{'key1': 'value1', 'key2': 'value2', 'key3': 'value3', 'key4': 'value4'}


In [ ]:
# 7.	Python – Convert key-values list to flat dictionary
lst = [('key1', 'value1'), ('key2', 'value2'), ('key3', 'value3')]
s=dict(lst)
s

{'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}

In [ ]:
votes = ['Candidate A', 'Candidate B', 'Candidate A', 'Candidate C', 'Candidate A', 'Candidate B', 'Candidate A']
for i in votes:
  a=(i,'--->',votes.count(i))

  print('winnig election candidate is ',a)
  break

winnig election candidate is  ('Candidate A', '--->', 4)


In [ ]:
# 14.	Handling missing keys in Python dictionaries
# to handle the missing values in dictionary we can use .get and .setdefault method and just explicitly define the values as default

my_dict = {'key1': 'value1', 'key2': 'value2'}

value = my_dict.setdefault('key3', 'Default Value')

print(value)
print(my_dict)


Default Value
{'key1': 'value1', 'key2': 'value2', 'key3': 'Default Value'}


In [ ]:
# 16.	Print anagrams together in Python using List and Dictionary
from collections import defaultdict

words = ['cat', 'dog', 'tac', 'god', 'act']

anagram_groups = defaultdict(list)

# Group words by their sorted letters
for word in words:
    sorted_word = ''.join(sorted(word))
    anagram_groups[sorted_word].append(word)

# Print the anagram groups
for group in anagram_groups.values():
    print(group)


['cat', 'tac', 'act']
['dog', 'god']


In [ ]:
# 22.	Counting the frequencies in a list using dictionary in Python
lst = ['apple', 'banana', 'apple', 'orange', 'banana', 'apple']
for i in lst:
  print(i,'===>',lst.count(i))


apple ===> 3
banana ===> 2
apple ===> 3
orange ===> 1
banana ===> 2
apple ===> 3


In [ ]:
input_string = input("Enter a string: ")
compressed_output = ""

count = 1
for i in range(len(input_string)):
    if i < len(input_string) - 1 and input_string[i] == input_string[i+1]:
        count += 1
    else:
        compressed_output += str(count) + input_string[i]
        count = 1

print(compressed_output)


Enter a string: aaabbc
3a2b1c


In [ ]:
input_string = input("Enter a string: ")

for i in input_string:
  print(input_string.count(i),i,end='')




Enter a string: aaabbc
3 a3 a3 a2 b2 b1 c

In [ ]:
input='niranjaniarrr'
l=[]
for i in input:
  l.append(i)

l1=set(l)
for i in l1:
  print(i,'===>',l.count(i))




a ===> 3
i ===> 2
j ===> 1
n ===> 3
r ===> 4


In [ ]:
a={1:'a',2:'b',3:'c'}
a.items()


dict_items([(1, 'a'), (2, 'b'), (3, 'c')])